= Terminal: WiFi Password
:hp-tags: fedora, ubuntu, linux, wifi, password, alias, cli, terminal

As a budding Linux Engineer I have found that the command line is often a very useful tool. You can get information faster and with greater detail. Often times for the information needed, there is no app with a GUI to provide it. Knowing a decent amount of commands, improves performance and efficiency by a great deal. 

One particular example of this is my constant need to retrieve the WiFi passwords of the networks I have already connected to. Of course, storing them in a file is a good way to keep them, but it is also a redundant method, due to linux systems already storing them in files.

I have utilized the command line to get the desired output. However, it would be time consuming and strenuous to be typing a lengthy command multiple times per day, even if I were to press ⬆ to travel through my terminal's history or do `history | grep [name of word in command here]` to filter the list of recently entered commands. A beautiful solution to this is simply to use the `alias` command to store frequently used commands and comand combinations. Below is the result of my contemplations. I will explain them after. It is worth mentioning that the directories/paths we are accessing requires *superuser* privileges, so tread carefully.

[[app-listing]]
[source,bash]
.wifipass, on fedora25
----
alias wifipass="{(sudo ls /etc/sysconfig/network-scripts/ | grep 'keys-') && (sudo cat /etc/sysconfig/network-scripts/keys-*)} | pr --column 2 -Tt"
----

In Fedora, the network passwords (PSK or Pre-Shared Key) is stored in separate files for each network. However, the network name (SSID, or Service Set IDentifier) is within the filename itself, prefixed by `keys-`. The first part of the command (`sudo ls /etc/sysconfig/network-scripts/ | grep 'keys-')`) is to retrieve the existing SSIDs, the second part of the script (`sudo cat /etc/sysconfig/network-scripts/keys-*`) is to retrieve the PSKs of each network. As the directory tree is traversed the order will remain consistent, therefore the order the SSIDs are returned is the same order the PSKs will be returned. However, the SSIDs will be listed first then the PSKs. Because of this we use `pr` to format the text into 2 columns. The `2` is the number of columns and the `-Tt` are the two options passed which omit pagination and omit the header respectively.

[[app-listing]]
[source,bash]
.wifipass, on ubuntu16.10
----
alias wifipass="sudo cat /etc/NetworkManager/system-connections/* | grep -e ssid -e psk"
----
In Ubuntu, all network configuration is stored inside separate files but the SSIDs are in the respective files, along with the PSKs. This allows us to retrieve what we need with a bit less hassle. Therefore, the command retrieves all the text in each file then filters for lines containing only `ssisd` and `psk`.


[quote, Christopher Lee Murray]
____
Often times the information needed, there is no app with a GUI to provide it.
____

[footer]
NB:

* `alias` is used to store commands that you often use to make your CLI life easier.
* `*` is the "wildcard" symbol which I will speak on more in a REGEX post later.
* Should you need to store these commands permanently (to used them after every boot) then you would need to store them in your `~/.bashrc` or your `~/.zhrc` file depending on your shell/
